name: Deploy Terraform

on:
  workflow_run:
    workflows: ["Build Docker Image"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Change directory to terraform
        run: cd terraform

      - name: Terraform Init
        run: terraform init
        working-directory: terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_VAR_aws_region: ${{ secrets.AWS_REGION }}
          TF_VAR_vpc_id: ${{ secrets.VPC_ID }}
          TF_VAR_subnet_id: ${{ secrets.SUBNET_ID }}

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_VAR_aws_region: ${{ secrets.AWS_REGION }}
          TF_VAR_vpc_id: ${{ secrets.VPC_ID }}
          TF_VAR_subnet_id: ${{ secrets.SUBNET_ID }}

      - name: Get Instance IP
        id: get_ip
        run: |
          INSTANCE_IP=$(terraform output -raw ec2_instance_public_ip | grep -Eo '([0-9]{1,3}\.){3}[0-9]{1,3}')
          echo "INSTANCE_IP=$INSTANCE_IP" | tee -a $GITHUB_ENV $GITHUB_OUTPUT
        working-directory: terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Verify GITHUB_ENV and GITHUB_OUTPUT
        run: |
          echo "Contents of GITHUB_ENV:"
          cat $GITHUB_ENV
          echo "Contents of GITHUB_OUTPUT:"
          cat $GITHUB_OUTPUT

      - name: Debug Outputs
        run: |
          echo "Final Instance IP: $INSTANCE_IP"
