name: Liveliness Check

on:
  workflow_run:
    workflows: ["Deploy Terraform"]
    types:
      - completed

jobs:
  check:
    runs-on: ubuntu-latest

    needs: deploy

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Debug Deploy Outputs
        run: |
          echo "Deploy Job Outputs:"
          echo "Instance IP: ${{ needs.deploy.outputs.instance_ip }}"

      - name: Run Liveliness Check
        run: |
          INSTANCE_IP=${{ needs.deploy.outputs.instance_ip }}
          echo "Checking http://$INSTANCE_IP:9000"
          curl --fail http://$INSTANCE_IP:9000 || exit 1
